### ISSUE TITLE
ceph doesnt work out the box, heres the fix

### ISSUE THREAD

**Issue by xahare** [rgl/proxmox-ve#1]
pveceph init wont work because it sees "127.0.0.1 hostname" in the first line of /etc/hosts. this line in provision.sh fixes it. 

`sed -i "/^127\.0\.0\.1.\+${fqdn}/d" /etc/hosts`

**Comment by rgl** [comment]
I never used Ceph, can you create an example vagrant environment for testing it out? Something like the one in the [example](https://github.com/rgl/proxmox-ve/tree/master/example) directory?

**Comment by xahare** [comment]
seems it was an issue in ceph, which gets the latest version when you run "pveceph install"

these commands now work without the workaround.

```
echo y | pveceph install
pveceph init
```

but i cant get past that due to what might be a bug in proxmox.

**Comment by rgl** [comment]
If you find a solution, let me known. I also want to learn more about Ceph. Having a working vagrant environment would be really nice.

**Comment by xahare** [comment]
here you go, https://github.com/xahare/pveceph

sometimes pvecluster fails. you can check that with "ls /etc/pve" or "systemctl list-units --failed". usually "vagrant destroy -f && vagrant up" will fix it.
