### ISSUE TITLE
[Help wanted] Increasing space for disks

### ISSUE THREAD

**Issue by rsmit-quintor** [rgl/proxmox-ve#10]
Hi,

I'm pretty new to using both Vagrant and Proxmox, but everything is working fine for me (using libvirt). 
The only issue I have is that I don't understand how I can increase the storage size for Proxmox (or, to be more exact, the disks within Proxmox) so that I can upload a 1.5GB VM back-up to "local" for example. 

I've tried to follow the instructions here: https://pve.proxmox.com/wiki/Resize_disks but I think the project wasn't built with enough storage space to begin with.
I then tried to increase the "disk_size": "15375" value inside proxmox-ve.json, run "vagrant halt" inside ./example and then run "make build-libvirt" again inside the project directory but it seems this doesn't increase the storage Proxmox has access to either.

Is there something else I can do to set up Proxmox through this project with more storage space (in the "local" disk")?

**Comment by rgl** [comment]
Modifying `disk_size` inside `proxmox-ve.json` should have worked.

Before trying a `vagrant up` again, did you do the following steps?

1. Did you redo the `vagrant box add` step?
2. Did you removed the `proxmox-ve-amd64_vagrant_box_image_0.img` volume from libvirt storage? This volume (notice its size):
![image](https://user-images.githubusercontent.com/43356/104090895-a8b2bc00-5271-11eb-8681-eca01873e70f.png)

Other way is to use the vagrant-libvirt `machine_virtual_size` to resize the VM disk size (this way you do not need to modify the base box), then re-create the vagrant environment (`vagrant destroy`, then `vagrant up`) like I just did at https://github.com/rgl/proxmox-ve/commit/ae3cbaa3c8b6348ea8c7fd8d1db7aba4c69b98d5.

**Comment by rsmit-quintor** [comment]
Thank you very much for the instructions! I haven't tried the things you mentioned. I'll try them later today or tomorrow and I'll let you know if it worked :)

**Comment by rsmit-quintor** [comment]
I managed to increase the size for vda3 using your instructions, so thank you very much!
I haven't managed to increase the size for the "local" disk yet though, but I'll try and get that to work in the coming days as well.
I also haven't managed to access proxmox through the Virtual Machine Manager like you showed but I don't think that's something I really need right now.

**Comment by rgl** [comment]
did you manage to get this working?

**Comment by Rerbun** [comment]
Sort of. Feel free to close this, we decided to take a different approach to our project.

**Comment by rsmit-quintor** [comment]
Sort of. We decided to take a different approach to our project, thank you for the help though!
