### ISSUE TITLE
Publish proxmox boxes  to Vagrant catalog

### ISSUE THREAD

**Issue by jottr** [rgl/proxmox-ve#11]
It's a shame that there is no quality and up to date Vagrant box available on the official Vagrant catalog.
Have you considered building the boxes via Github Actions and then publishing them to Github Actions?

**Comment by rgl** [comment]
I once did, but GitHub Actions only had nested virtualization using VirtualBox on their older macOS runners. [This is something they are not actually thinking in having](https://github.com/actions/virtual-environments/issues/183#issuecomment-706244929).

**Comment by jottr** [comment]
Totally forgot that we actually need Virtualbox to build the image. My bad. Sorry for the noise.
