### ISSUE TITLE
packer build hangs at EULA

### ISSUE THREAD

**Issue by abbbi** [rgl/proxmox-ve#15]
hi,

not sure if intended, but building with the latest proxmox version the packer build hangs at EULA, see screenshot..

**Comment by abbbi** [comment]
![eula2](https://user-images.githubusercontent.com/3919561/134561821-35b08198-7070-4319-9e32-c4cbac5e07be.jpg)

**Comment by rgl** [comment]
It should wait 1m until it presses the Next button. See the summary steps and wait times at https://github.com/rgl/proxmox-ve#packer-boot_command. If after a minute it still does not work, could it be that in your setup it takes more than one minute to reach that screen? If so, you might need to increase the wait time.

**Comment by rgl** [comment]
Closing, as I believe the last comment should have made it work.
