### ISSUE TITLE
Cannot install with VirtualBox 7 on macOS

### ISSUE THREAD

**Issue by ianhinder** [rgl/proxmox-ve#23]
I am trying to install proxmox 7.4 from this repository (commit b7ca086511e9e1f87c017846b0339dd23e408fee) with VirtualBox on macOS.  However, as soon as the PVE installer starts, it opens a dialog box with "No support for KVM virtualization detected".  This messes up the Packer boot_command sequence, but presumably also means that KVM VMs won't work even if the boot_command is adjusted.  This is with VirtualBox 7.0.6 on macOS 12.5.1 with an Intel i7.  The "Enable Nested VT-x/AMD-V" option is enabled in the machine settings.  VirtualBox has [switched](https://www.virtualbox.org/wiki/Changelog) to using native macOS virtualisation interfaces rather than a kernel extension - could this be related?
> macOS host: Dropped all kernel extensions. [VirtualBox](https://www.virtualbox.org/wiki/VirtualBox) relies fully on the hypervisor and vmnet frameworks provided by Apple now. At the moment the implementation lacks "Internal Networking" functionality. This will be provided at a later date.

**Comment by rgl** [comment]
Closing this issue because I no longer use VirtualBox. Support was dropped support in https://github.com/rgl/proxmox-ve/commit/b51b7d4f8aa3975f809511e26ec9766b69724bb5.
