### ISSUE TITLE
Hangs forever on MacOS

### ISSUE THREAD

**Issue by zMynxx** [rgl/proxmox-ve#26]
System:
MacOS Sonoma 14.2.1

The issue: 
Seems to hang after typing the email address.

Steps to reproduce:
```bash
brew install packer vagrant
cd /proxmox-ve
make build-virtualbox
```

Images:
<img width="1198" alt="Screenshot 2024-01-19 at 22 16 28" src="https://github.com/rgl/proxmox-ve/assets/124557045/d829852f-2531-4850-b885-442ebfeb9f90">
<img width="748" alt="Screenshot 2024-01-19 at 22 17 30" src="https://github.com/rgl/proxmox-ve/assets/124557045/bc0f67ba-91c0-474b-a050-3a78a41a2453">

Log file:
[proxmox-ve-amd64-virtualbox.box.log](https://github.com/rgl/proxmox-ve/files/13994265/proxmox-ve-amd64-virtualbox.box.log)

**Comment by rgl** [comment]
the proxmox installer has some odd behaviours. in your case, it seems the country autodection feature did not finish in the wait time that is defined in the packer boot_command. so you have update the wait for boot step timeout to 10m (or more) for example, and see whether it helps.

**Comment by zMynxx** [comment]
Assuming I've understood correctly I've change line 407 of 'proxmox-ve.pkr.hcl' `boot_wait` from `5s` to `10m`.
Results seems to be the same. 
<img width="748" alt="Screenshot 2024-01-20 at 18 06 58" src="https://github.com/rgl/proxmox-ve/assets/124557045/487bdd1f-1d5d-4aba-8c09-af11d2212da9">

**Comment by rgl** [comment]
Just changing the `boot_command` should have been enough. But like you tried, it didn't do the trick.

Before going further with packer. Try to manually create a VM in VirtualBox with the Proxmox iso, and go thru the manual installation, to see if that also happens.

**Comment by rgl** [comment]
Closing this issue because I no longer use VirtualBox. Support was dropped in https://github.com/rgl/proxmox-ve/commit/b51b7d4f8aa3975f809511e26ec9766b69724bb5.
