### ISSUE TITLE
firefox: SEC_ERROR_REUSED_ISSUER_AND_SERIAL

### ISSUE THREAD

**Issue by xahare** [rgl/proxmox-ve#3]
sometimes the browser notices the same serial number on the tls cert in the vagrant box and complains about this, throwing SEC_ERROR_REUSED_ISSUER_AND_SERIAL

in [this message](https://forum.proxmox.com/threads/strange-bug-in-5b2-pvesh-disables-the-web-ui.35016/#post-172303) a proxmox dev suggested deleting the root cert to cause it to generate a new one on boot. i asked for clarification on exactly which files to delete and ill update this issue when i get that. 

my workaround for now is putting this line before the "clean packages" section in provision.sh

rm -f /etc/pve/*key /etc/pve/*.pem /etc/pve/priv/*key /etc/pve/priv/*.srl

**Comment by rgl** [comment]
My intent is to use a custom CA to generate the certificates once and re-use them between vagrant destroy/up.

**Comment by xahare** [comment]
Would the same cert show up on different vagrant runs?

**Comment by rgl** [comment]
Yes, that is the intent. Being able to re-create the environment with the same certificates.

**Comment by xahare** [comment]
should have mentioned this earlier, ive been able to reliably trigger it with your pve ceph cluster.

1. vagrant up --no-parallel
2. firefox https://10.1.0.203:8006/ just get to the log in page, dont need to actually log in
3. vagrant destroy -f
4. vagrant up --no-parallel
5. firefox https://10.1.0.203:8006/ this time, it wont load the login page until you delete the saved CA

im glad you made provision-storage.sh a separate file

**Comment by rgl** [comment]
FYI, I'm now reusing the certificates between node creation at https://github.com/rgl/proxmox-ve-cluster-vagrant. I'll later do a simpler version of it in this repo too.

**Comment by rgl** [comment]
fixed at https://github.com/rgl/proxmox-ve/commit/b7d171bb35380578318eae3ce3c23fb206246aa7
